Add link for audio attachment, show file's name and size
clbn/freefeed-delta pull request #28
Opened 2022-06-27 11:55 UTC by paraketsova

2022-06-27 14:25 UTC, paraketsova commented
![image](https://user-images.githubusercontent.com/66638374/175964480-cdde410c-62d9-4991-83a9-ea125a645af2.png)

2022-06-27 17:13 UTC, clbn requested changes
LGTM, except for some nitpicking on extra spaces.

2022-06-27 17:13 UTC, clbn commented on components/PostAttachments.js
> +
Let's remove these spaces (don't remove the newline tho).

2022-06-27 17:13 UTC, clbn commented on components/PostAttachments.js
> +
Please remove these new empty lines in `PostAttachments`.

2022-06-27 17:13 UTC, clbn commented on components/AttachmentOther.js
> +
Extra line here.

2022-06-27 17:17 UTC, clbn commented on components/PostAttachments.js
> +  for (let attachmentId of attachmentIds) {
Also, I this `let` should be `const`.

2022-06-27 17:18 UTC, clbn commented on components/PostAttachments.js
> +    if (attachments[attachmentId].mediaType && attachments[attachmentId].mediaType === 'image') {
I don't think the first condition adds anything here, the second one is enough.

2022-06-28 18:01 UTC, clbn approved these changes
Thanks, looks good!

2022-06-28 18:02 UTC, merged